# Generated by Django 4.2.6 on 2024-04-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Functionalarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Rolename",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "functionalarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.functionalarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("stakeholder_name", models.CharField(max_length=100)),
                ("stakeholder_type", models.CharField(max_length=100)),
                ("county", models.CharField(max_length=100)),
                ("hiv", models.CharField(max_length=255)),
                ("malaria", models.CharField(max_length=200)),
                ("fp", models.CharField(max_length=125)),
                ("mnch", models.CharField(max_length=125)),
                ("emms", models.CharField(max_length=125)),
                ("contact_email", models.CharField(max_length=125)),
                ("notes", models.CharField(max_length=500)),
                ("activity_reference", models.CharField(max_length=150)),
                (
                    "functionalarea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webapp.functionalarea",
                    ),
                ),
                (
                    "rolename",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webapp.rolename",
                    ),
                ),
            ],
        ),
    ]
