# Generated by Django 4.2.13 on 2024-06-28 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Primary_contact_tel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='budget',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='entry_level',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('County', 'County')], null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='partner_category',
            field=models.CharField(blank=True, choices=[('Implementing', 'Implementing'), ('Contracted', 'Contracted'), ('Funder', 'Funder')], null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='partnership_framework',
            field=models.CharField(blank=True, choices=[('MOU', 'National'), ('Implementation Letter', 'Implementation Letter'), ('Letter of Intent', 'Letter of Intent'), ('Partnership Agreement', 'Partnership Agreement'), ('Implementation Letter', 'Implementation Letter'), ('Contract', 'Contract'), ('Other', 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='physical_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('Profit', 'Profit'), ('Non Profit', 'Non Profit')], null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='year_of_registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='county',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='record',
            name='emms',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='fp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='hiv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='malaria',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='mnch',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.TextField(max_length=500),
        ),
    ]
